SELECT --*
 FA.ASSET_NUMBER AS 资产编号,
 --FA.SERIAL_NUMBER,
 --FA.CATEGORY_TYPE,
 FA.DESCRIPTION AS 资产描述,
 FA.ASSET_TYPE AS 资产分类 /*(固定、无形、长摊、在建）*/,
 FA.ATTRIBUTE_CATEGORY_CODE AS 资产种类 /*（小类细分）*/,
 GCC.SEGMENT2 AS 所属成本中心,
 FBBC.ORIGINAL_COST AS 资产价值,
 FBBC.COST - (SELECT SUM(FFI.DEPRN_AMOUNT)
                FROM FA_FINANCIAL_INQUIRY_DEPRN_V FFI
               WHERE 1 = 1
                 AND FFI.ASSET_ID = FA.ASSET_ID) AS 资产净值,
 --999999 AS 资产相关业务,
 FBBC.LIFE_IN_MONTHS AS 资产使用年限月,
 --SYSDATE - FBBC.DATE_PLACED_IN_SERVICE AS 资产已折旧年限,
 FBBC.SALVAGE_VALUE          AS 折旧残值,
 FBBC.DATE_PLACED_IN_SERVICE AS 投入使用时间,
 
 (SELECT SUM(FFI.DEPRN_AMOUNT)
    FROM FA_FINANCIAL_INQUIRY_DEPRN_V FFI
   WHERE 1 = 1
     AND FFI.ASSET_ID = FA.ASSET_ID) AS 累计折旧

  FROM FA_ADDITIONS_V           FA,
       FA_BOOKS_BOOK_CONTROLS_V FBBC,
       GL_CODE_COMBINATIONS     GCC,
       FA_DISTRIBUTION_HISTORY  FDH
 WHERE 1 = 1
   AND FA.ASSET_ID = FBBC.ASSET_ID
   --AND FA.ASSET_NUMBER = 'H128-001' --'716-019-01' --'811-071'
      --AND FBBC.DATE_PLACED_IN_SERVICE > SYSDATE - 360
   AND FBBC.DATE_INEFFECTIVE IS NULL
   AND FBBC.BOOK_TYPE_CODE IN
       (SELECT BOOK_TYPE_CODE FROM FA_BOOK_CONTROLS_SEC)
   AND FDH.ASSET_ID = FA.ASSET_ID
   AND GCC.CODE_COMBINATION_ID = FDH.CODE_COMBINATION_ID
   AND fdh.BOOK_TYPE_CODE = 'HNET_资产账簿'
   AND fdh.DATE_INEFFECTIVE IS NULL;
   
   
SELECT *
  FROM GL_CODE_COMBINATIONS GCC
 WHERE GCC.CODE_COMBINATION_ID IN (3879170, 3830169);
