SELECT *
  FROM APPS.ORG_ORGANIZATION_DEFINITIONS OOD
 WHERE 1 = 1
   AND OOD.ORGANIZATION_NAME LIKE '%_ZJ_%浙江省本部%';

SELECT HOU.ORGANIZATION_ID ORG_ID, HOU.SHORT_CODE, HOU.*
  FROM APPS.HR_OPERATING_UNITS HOU
 WHERE 1 = 1
   AND HOU.NAME LIKE '%_ZJ_%'
 ORDER BY HOU.BUSINESS_GROUP_ID, HOU.SHORT_CODE;

--Vision China
/*
organization_id 4555
*/

SELECT *
  FROM RA_CUSTOMER_TRX_ALL RCT
 WHERE 1 = 1
   AND RCT.ORG_ID = 4555;
