SELECT transaction_date,
       base_transaction_value,
       revision,
       transaction_type_name,
       operation_seq_num,
       department_code,
       resource_seq_num,
       subinventory_code,
       transaction_id,
       currency_code,
       transaction_value,
       currency_conversion_rate,
       currency_conversion_type,
       currency_conversion_date,
       line_type_name,
       transaction_source,
       primary_uom,
       primary_quantity,
       wip_entity_name,
       line_code,
       basis,
       reason_name,
       reference,
       gl_batch_id,
       resource_code,
       cost_element,
       transaction_quantity,
       transaction_uom,
       rate_or_amount,
       unit_cost,
       organization_id,
       wip_entity_id,
       primary_item_id,
       line_id,
       acct_period_id,
       inventory_item_id,
       reference_account,
       repetitive_schedule_id,
       contra_set_id,
       activity,
       overhead_basis_factor,
       basis_resource_id
  FROM cst_distribution_v v
  ,gl_code_combinations gcc
 WHERE organization_id = 86
 AND gcc.code_combination_id = v.
   AND nvl(basis_resource_id, 0) <> -1
   AND (transaction_id = 20771589)
 ORDER BY transaction_date DESC,
          transaction_id DESC,
          sign(base_transaction_value) DESC,
          abs(base_transaction_value) DESC
