DROP TABLE xxmrp.XXMRP_WEBADI_FORECAST_INT;

DROP Index XXMRP.XXMRP_WEBADI_FORECAST_INT_U1;

DROP Index XXMRP.XXMRP_WEBADI_FORECAST_INT_U2;

create SEQUENCE XXMRP_FRCST_GRP_NUM_S
minvalue 1
maxvalue 9999999999999999999999999999
start with 1
increment by 1
cache 1000;

create synonym CUX_OE_ORDER_LINES_ALL for cux.CUX_OE_ORDER_LINES_ALL;

-- Create table
-- refer to MRP_FORECAST_DATES_V
create table XXMRP.XXMRP_WEBADI_FORECAST_INT
(
  OBJECT_VERSION_NUMBER   NUMBER,
  CREATED_BY              NUMBER,
  CREATION_DATE           DATE,
  LAST_UPDATED_BY         NUMBER not null,
  LAST_UPDATE_DATE        DATE not null,
  LAST_UPDATE_LOGIN       NUMBER,
  WEBADI_RUN_ID           NUMBER,
  WEBADI_ROW_INDEX        NUMBER,
  WEBADI_GROUP_NUMBER     VARCHAR2(100),
  ACTION_TYPE             VARCHAR2(10),
  PROCESS_FLAG            VARCHAR2(1) default 'P',
  ERROR_MESSAGE           VARCHAR2(4000),
  
  --Business column
  FORECAST_DESIGNATOR     VARCHAR2(10),--Forecast Set
  INVENTORY_ITEM_ID       NUMBER,--get CONCATENATED_SEGMENTS, DESCRIPTION, PRIMARY_UOM_CODE, BOM_ITEM_TYPE, PICK_COMPONENTS_FLAG from MTL_SYSTEM_ITEMS_VL
  BUCKET_TYPE             NUMBER,
  FORECAST_DATE           DATE,
  RATE_END_DATE           DATE,
  CURRENT_FORECAST_QUANTITY NUMBER,
  ORGANIZATION_ID         NUMBER,
  comments  varchar2(240),
------------------------------------------
  ATTRIBUTE_CATEGORY    VARCHAR2(240),
  ATTRIBUTE1            VARCHAR2(240),
  ATTRIBUTE2            VARCHAR2(240),
  ATTRIBUTE3            VARCHAR2(240),
  ATTRIBUTE4            VARCHAR2(240),
  ATTRIBUTE5            VARCHAR2(240),
  ATTRIBUTE6            VARCHAR2(240),
  ATTRIBUTE7            VARCHAR2(240),
  ATTRIBUTE8            VARCHAR2(240),
  ATTRIBUTE9            VARCHAR2(240),
  ATTRIBUTE10           VARCHAR2(240),
  ATTRIBUTE11           VARCHAR2(240),
  ATTRIBUTE12           VARCHAR2(240),
  ATTRIBUTE13           VARCHAR2(240),
  ATTRIBUTE14           VARCHAR2(240),
  ATTRIBUTE15           VARCHAR2(240)
) tablespace APPS_TS_TX_DATA;

-- Create index
Create Unique Index XXMRP.XXMRP_WEBADI_FORECAST_INT_U1 On XXMRP.XXMRP_WEBADI_FORECAST_INT(WEBADI_RUN_ID, WEBADI_ROW_INDEX) tablespace APPS_TS_TX_IDX;

Create Unique Index XXMRP.XXMRP_WEBADI_FORECAST_INT_U2 On XXMRP.XXMRP_WEBADI_FORECAST_INT(WEBADI_GROUP_NUMBER, WEBADI_ROW_INDEX) tablespace APPS_TS_TX_IDX;

-- Custom unique index to validate duplicate records upload error
--Create Unique Index XXMRP.XXMRP_WEBADI_FORECAST_INT_U3 On XXMRP.XXMRP_WEBADI_FORECAST_INT(WEBADI_GROUP_NUMBER, ORGANIZATION_ID, INVENTORY_ITEM_ID, CATEGORY_SET_NAME, CATEGORY_NAME) tablespace APPS_TS_TX_IDX;

-- Create synonym
Create Synonym apps.XXMRP_WEBADI_FORECAST_INT For XXMRP.XXMRP_WEBADI_FORECAST_INT;

