/*CREATE OR REPLACE VIEW MTL_PHYSICAL_INVENTORY_TAGS_V AS*/
SELECT m.rowid                        row_id,
       m.tag_id,
       m.physical_inventory_id,
       m.organization_id,
       m.last_update_date,
       m.last_updated_by,
       m.creation_date,
       m.created_by,
       m.last_update_login,
       m.void_flag,
       m.tag_number,
       m.adjustment_id,
       m.inventory_item_id,
       msi.description                item_description,
       msi.revision_qty_control_code,
       msi.lot_control_code,
       msi.serial_number_control_code,
       msi.location_control_code,
       m.tag_quantity,
       m.tag_uom,
       m.tag_quantity_at_standard_uom,
       m.standard_uom,
       m.subinventory,
       m.locator_id,
       m.lot_number,
       m.revision,
       m.serial_num,
       m.counted_by_employee_id,
       m.attribute_category,
       m.attribute1,
       m.attribute2,
       m.attribute3,
       m.attribute4,
       m.attribute5,
       m.attribute6,
       m.attribute7,
       m.attribute8,
       m.attribute9,
       m.attribute10,
       m.attribute11,
       m.attribute12,
       m.attribute13,
       m.attribute14,
       m.attribute15,
       m.parent_lpn_id,
       m.outermost_lpn_id,
       lpn1.license_plate_number      parent_lpn,
       lpn2.license_plate_number      outermost_lpn,
       lpn1.inventory_item_id         container_item_id,
       lpn1.revision                  container_revision,
       lpn1.lot_number                container_lot_number,
       lpn1.serial_number             container_serial_number,
       m.cost_group_id,
       cg.cost_group                  cost_group_name,
       lpn1.cost_group_id             container_cost_group_id,
       cg2.cost_group                 container_cost_group_name,
       m.lot_expiration_date,
       msi.shelf_life_days,
       msi.shelf_life_code,
       m.tag_secondary_quantity,
       m.tag_secondary_uom,
       m.tag_qty_at_std_secondary_uom,
       m.standard_secondary_uom
  FROM mtl_physical_inventory_tags m,
       mtl_system_items            msi,
       wms_license_plate_numbers   lpn1,
       wms_license_plate_numbers   lpn2,
       cst_cost_groups             cg,
       cst_cost_groups             cg2
 WHERE m.inventory_item_id = msi.inventory_item_id(+)
   AND m.organization_id = msi.organization_id(+)
   AND m.parent_lpn_id = lpn1.lpn_id(+)
   AND m.outermost_lpn_id = lpn2.lpn_id(+)
   AND m.cost_group_id = cg.cost_group_id(+)
   AND lpn1.cost_group_id = cg2.cost_group_id(+);
