SELECT --*
 mp.material_account,
 xxhkm_common_utl.get_acc_cate(ood.chart_of_accounts_id, mp.material_account) material_account,
 xxhkm_common_utl.get_ccid_segments(ood.chart_of_accounts_id, mp.material_account) material_account,
 xxhkm_common_utl.get_ccid_description(ood.chart_of_accounts_id, mp.material_account) material_account,
 mp.outside_processing_account,
 xxhkm_common_utl.get_acc_cate(ood.chart_of_accounts_id, mp.outside_processing_account) outside_processing_account,
 xxhkm_common_utl.get_ccid_segments(ood.chart_of_accounts_id, mp.outside_processing_account) outside_processing_account,
 xxhkm_common_utl.get_ccid_description(ood.chart_of_accounts_id, mp.outside_processing_account) outside_processing_account,
 mp.material_overhead_account,
 xxhkm_common_utl.get_acc_cate(ood.chart_of_accounts_id, mp.material_overhead_account) material_overhead_account,
 xxhkm_common_utl.get_ccid_segments(ood.chart_of_accounts_id, mp.material_overhead_account) material_overhead_account,
 xxhkm_common_utl.get_ccid_description(ood.chart_of_accounts_id, mp.material_overhead_account) material_overhead_account,
 mp.overhead_account,
 xxhkm_common_utl.get_acc_cate(ood.chart_of_accounts_id, mp.overhead_account) overhead_account,
 xxhkm_common_utl.get_ccid_segments(ood.chart_of_accounts_id, mp.overhead_account) overhead_account,
 xxhkm_common_utl.get_ccid_description(ood.chart_of_accounts_id, mp.overhead_account) overhead_account,
 mp.resource_account,
 xxhkm_common_utl.get_acc_cate(ood.chart_of_accounts_id, mp.resource_account) resource_account,
 xxhkm_common_utl.get_ccid_segments(ood.chart_of_accounts_id, mp.resource_account) resource_account,
 xxhkm_common_utl.get_ccid_description(ood.chart_of_accounts_id, mp.resource_account) resource_account,
 mp.expense_account,
 xxhkm_common_utl.get_acc_cate(ood.chart_of_accounts_id, mp.expense_account) expense_account,
 xxhkm_common_utl.get_ccid_segments(ood.chart_of_accounts_id, mp.expense_account) expense_account,
 xxhkm_common_utl.get_ccid_description(ood.chart_of_accounts_id, mp.expense_account) expense_account,
 mp.interorg_transfer_cr_account,
 xxhkm_common_utl.get_acc_cate(ood.chart_of_accounts_id, mp.interorg_transfer_cr_account) interorg_transfer_cr_account,
 xxhkm_common_utl.get_ccid_segments(ood.chart_of_accounts_id, mp.interorg_transfer_cr_account) interorg_transfer_cr_account,
 xxhkm_common_utl.get_ccid_description(ood.chart_of_accounts_id, mp.interorg_transfer_cr_account) interorg_transfer_cr_account,
 mp.interorg_price_var_account,
 xxhkm_common_utl.get_acc_cate(ood.chart_of_accounts_id, mp.interorg_price_var_account) interorg_price_var_account,
 xxhkm_common_utl.get_ccid_segments(ood.chart_of_accounts_id, mp.interorg_price_var_account) interorg_price_var_account,
 xxhkm_common_utl.get_ccid_description(ood.chart_of_accounts_id, mp.interorg_price_var_account) interorg_price_var_account,
 mp.interorg_receivables_account,
 xxhkm_common_utl.get_acc_cate(ood.chart_of_accounts_id, mp.interorg_receivables_account) interorg_receivables_account,
 xxhkm_common_utl.get_ccid_segments(ood.chart_of_accounts_id, mp.interorg_receivables_account) interorg_receivables_account,
 xxhkm_common_utl.get_ccid_description(ood.chart_of_accounts_id, mp.interorg_receivables_account) interorg_receivables_account,
 mp.interorg_payables_account,
 xxhkm_common_utl.get_acc_cate(ood.chart_of_accounts_id, mp.interorg_payables_account) interorg_payables_account,
 xxhkm_common_utl.get_ccid_segments(ood.chart_of_accounts_id, mp.interorg_payables_account) interorg_payables_account,
 xxhkm_common_utl.get_ccid_description(ood.chart_of_accounts_id, mp.interorg_payables_account) interorg_payables_account,
 mp.intransit_inv_account,
 xxhkm_common_utl.get_acc_cate(ood.chart_of_accounts_id, mp.intransit_inv_account) intransit_inv_account,
 xxhkm_common_utl.get_ccid_segments(ood.chart_of_accounts_id, mp.intransit_inv_account) intransit_inv_account,
 xxhkm_common_utl.get_ccid_description(ood.chart_of_accounts_id, mp.intransit_inv_account) intransit_inv_account,
 mp.purchase_price_var_account,
 xxhkm_common_utl.get_acc_cate(ood.chart_of_accounts_id, mp.purchase_price_var_account) purchase_price_var_account,
 xxhkm_common_utl.get_ccid_segments(ood.chart_of_accounts_id, mp.purchase_price_var_account) purchase_price_var_account,
 xxhkm_common_utl.get_ccid_description(ood.chart_of_accounts_id, mp.purchase_price_var_account) purchase_price_var_account,
 mp.invoice_price_var_account,
 xxhkm_common_utl.get_acc_cate(ood.chart_of_accounts_id, mp.invoice_price_var_account) invoice_price_var_account,
 xxhkm_common_utl.get_ccid_segments(ood.chart_of_accounts_id, mp.invoice_price_var_account) invoice_price_var_account,
 xxhkm_common_utl.get_ccid_description(ood.chart_of_accounts_id, mp.invoice_price_var_account) invoice_price_var_account,
 mp.ap_accrual_account,
 xxhkm_common_utl.get_acc_cate(ood.chart_of_accounts_id, mp.ap_accrual_account) ap_accrual_account,
 xxhkm_common_utl.get_ccid_segments(ood.chart_of_accounts_id, mp.ap_accrual_account) ap_accrual_account,
 xxhkm_common_utl.get_ccid_description(ood.chart_of_accounts_id, mp.ap_accrual_account) ap_accrual_account,
 mp.encumbrance_account,
 xxhkm_common_utl.get_acc_cate(ood.chart_of_accounts_id, mp.encumbrance_account) encumbrance_account,
 xxhkm_common_utl.get_ccid_segments(ood.chart_of_accounts_id, mp.encumbrance_account) encumbrance_account,
 xxhkm_common_utl.get_ccid_description(ood.chart_of_accounts_id, mp.encumbrance_account) encumbrance_account,
 mp.sales_account,
 xxhkm_common_utl.get_acc_cate(ood.chart_of_accounts_id, mp.sales_account) sales_account,
 xxhkm_common_utl.get_ccid_segments(ood.chart_of_accounts_id, mp.sales_account) sales_account,
 xxhkm_common_utl.get_ccid_description(ood.chart_of_accounts_id, mp.sales_account) sales_account,
 mp.cost_of_sales_account,
 xxhkm_common_utl.get_acc_cate(ood.chart_of_accounts_id, mp.cost_of_sales_account) cost_of_sales_account,
 xxhkm_common_utl.get_ccid_segments(ood.chart_of_accounts_id, mp.cost_of_sales_account) cost_of_sales_account,
 xxhkm_common_utl.get_ccid_description(ood.chart_of_accounts_id, mp.cost_of_sales_account) cost_of_sales_account,
 mp.project_cost_account,
 xxhkm_common_utl.get_acc_cate(ood.chart_of_accounts_id, mp.project_cost_account) project_cost_account,
 xxhkm_common_utl.get_ccid_segments(ood.chart_of_accounts_id, mp.project_cost_account) project_cost_account,
 xxhkm_common_utl.get_ccid_description(ood.chart_of_accounts_id, mp.project_cost_account) project_cost_account,
 mp.deferred_cogs_account,
 xxhkm_common_utl.get_acc_cate(ood.chart_of_accounts_id, mp.deferred_cogs_account) deferred_cogs_account,
 xxhkm_common_utl.get_ccid_segments(ood.chart_of_accounts_id, mp.deferred_cogs_account) deferred_cogs_account,
 xxhkm_common_utl.get_ccid_description(ood.chart_of_accounts_id, mp.deferred_cogs_account) deferred_cogs_account,
 mp.average_cost_var_account,
 xxhkm_common_utl.get_acc_cate(ood.chart_of_accounts_id, mp.average_cost_var_account) average_cost_var_account,
 xxhkm_common_utl.get_ccid_segments(ood.chart_of_accounts_id, mp.average_cost_var_account) average_cost_var_account,
 xxhkm_common_utl.get_ccid_description(ood.chart_of_accounts_id, mp.average_cost_var_account) average_cost_var_account,
 mp.lcm_var_account,
 xxhkm_common_utl.get_acc_cate(ood.chart_of_accounts_id, mp.lcm_var_account) lcm_var_account,
 xxhkm_common_utl.get_ccid_segments(ood.chart_of_accounts_id, mp.lcm_var_account) lcm_var_account,
 xxhkm_common_utl.get_ccid_description(ood.chart_of_accounts_id, mp.lcm_var_account) lcm_var_account,
 mp.borrpay_matl_var_account,
 xxhkm_common_utl.get_acc_cate(ood.chart_of_accounts_id, mp.borrpay_matl_var_account) borrpay_matl_var_account,
 xxhkm_common_utl.get_ccid_segments(ood.chart_of_accounts_id, mp.borrpay_matl_var_account) borrpay_matl_var_account,
 xxhkm_common_utl.get_ccid_description(ood.chart_of_accounts_id, mp.borrpay_matl_var_account) borrpay_matl_var_account,
 mp.borrpay_moh_var_account,
 xxhkm_common_utl.get_acc_cate(ood.chart_of_accounts_id, mp.borrpay_moh_var_account) borrpay_moh_var_account,
 xxhkm_common_utl.get_ccid_segments(ood.chart_of_accounts_id, mp.borrpay_moh_var_account) borrpay_moh_var_account,
 xxhkm_common_utl.get_ccid_description(ood.chart_of_accounts_id, mp.borrpay_moh_var_account) borrpay_moh_var_account,
 mp.borrpay_osp_var_account,
 xxhkm_common_utl.get_acc_cate(ood.chart_of_accounts_id, mp.borrpay_osp_var_account) borrpay_osp_var_account,
 xxhkm_common_utl.get_ccid_segments(ood.chart_of_accounts_id, mp.borrpay_osp_var_account) borrpay_osp_var_account,
 xxhkm_common_utl.get_ccid_description(ood.chart_of_accounts_id, mp.borrpay_osp_var_account) borrpay_osp_var_account,
 mp.borrpay_ovh_var_account,
 xxhkm_common_utl.get_acc_cate(ood.chart_of_accounts_id, mp.borrpay_ovh_var_account) borrpay_ovh_var_account,
 xxhkm_common_utl.get_ccid_segments(ood.chart_of_accounts_id, mp.borrpay_ovh_var_account) borrpay_ovh_var_account,
 xxhkm_common_utl.get_ccid_description(ood.chart_of_accounts_id, mp.borrpay_ovh_var_account) borrpay_ovh_var_account,
 mp.borrpay_res_var_account,
 xxhkm_common_utl.get_acc_cate(ood.chart_of_accounts_id, mp.borrpay_res_var_account) borrpay_res_var_account,
 xxhkm_common_utl.get_ccid_segments(ood.chart_of_accounts_id, mp.borrpay_res_var_account) borrpay_res_var_account,
 xxhkm_common_utl.get_ccid_description(ood.chart_of_accounts_id, mp.borrpay_res_var_account) borrpay_res_var_account,
 mp.cost_group_accounting,
 xxhkm_common_utl.get_acc_cate(ood.chart_of_accounts_id, mp.cost_group_accounting) cost_group_accounting,
 xxhkm_common_utl.get_ccid_segments(ood.chart_of_accounts_id, mp.cost_group_accounting) cost_group_accounting,
 xxhkm_common_utl.get_ccid_description(ood.chart_of_accounts_id, mp.cost_group_accounting) cost_group_accounting,
 
 mp.*
  FROM mtl_parameters               mp,
       org_organization_definitions ood
 WHERE 1 = 1
   AND ood.organization_id = mp.organization_id
   AND mp.organization_code = 'SG1';
