
--ar transaction
--ar header
SELECT RCT.ORG_ID,
       RCT.TRX_NUMBER,
       RCTT.NAME,
       RCTT.TYPE,
       RCT.LAST_UPDATE_DATE,
       RCT.ATTRIBUTE10,
       RCT.*
  FROM RA_CUSTOMER_TRX_ALL RCT, RA_CUST_TRX_TYPES_ALL RCTT
 WHERE 1 = 1
   AND RCTT.ORG_ID = RCT.ORG_ID
   AND RCTT.CUST_TRX_TYPE_ID = RCT.CUST_TRX_TYPE_ID
      --AND rct.customer_trx_id = 4890563--4865153
      --AND rctt.type IN ('CM', 'DM')
      AND rct.COMPLETE_FLAG = 'N'
   AND RCT.ORG_ID = 788--7905--84 --101 --84
      --AND rctt.name = ''
      --AND rct.trx_number IN ('JPE-18000315','600000000010')--('HKM2018092101') --('TFO000011')--('CTE1_454:TE_2004') --('JPE-18000050')--('10000017753')
   --AND RCT.TRX_NUMBER LIKE 'TFO000049'--'TFO000049' --'%6%10'
--AND rct.creation_date >= to_date('20180301','yyyymmdd')
--AND rct.creation_date <= to_date('20180315','yyyymmdd')
--AND rct.customer_trx_id = 4022542
 ORDER BY RCT.CREATION_DATE DESC;

SELECT *
  FROM RA_CUST_TRX_TYPES_ALL RCTT
 WHERE 1 = 1
   AND RCTT.ORG_ID = 84--101
   AND rctt.name = 'Invoice Only -V'
--AND rctt.cust_trx_type_id = 1350
;

SELECT *
  FROM XLA.XLA_TRANSACTION_ENTITIES XTE
 WHERE 1 = 1
   AND XTE.APPLICATION_ID = 222
   AND XTE.SOURCE_ID_INT_1 = 4292291 --3586252
;

SELECT *
  FROM XLA_AE_HEADERS XAH
 WHERE 1 = 1
   AND XAH.APPLICATION_ID = 222
   AND XAH.ENTITY_ID = 25134577;

SELECT RCT.CUSTOMER_TRX_ID,
       RCT.TRX_NUMBER,
       RCT.CREATION_DATE    RCT_CREATED,
       RCT.LAST_UPDATE_DATE RCT_UPDATE,
       XTE.CREATION_DATE    XTE_CREATED,
       XAH.CREATION_DATE    XAH_CREATED,
       XAH.GL_TRANSFER_DATE
  FROM RA_CUSTOMER_TRX_ALL          RCT,
       XLA.XLA_TRANSACTION_ENTITIES XTE,
       XLA_AE_HEADERS               XAH
 WHERE 1 = 1
   AND RCT.CUSTOMER_TRX_ID = XTE.SOURCE_ID_INT_1
   AND XTE.ENTITY_ID = XAH.ENTITY_ID
   AND XTE.APPLICATION_ID = 222 --AR
   AND RCT.TRX_NUMBER IN ('JPE-18000050') --('JPE-17000146', 'JPE-17000461')
;

SELECT --rct.previous_customer_trx_id,
 RCTL.DESCRIPTION, rctl.customer_trx_line_id,
 
 rctl.unit_selling_price,rctl.line_number,
 
 RCT.*, RCTL.*
  FROM RA_CUSTOMER_TRX_ALL RCT, RA_CUSTOMER_TRX_LINES_ALL RCTL
 WHERE 1 = 1
   AND RCT.CUSTOMER_TRX_ID = RCTL.CUSTOMER_TRX_ID
   AND RCT.TRX_NUMBER = 'TFO000049'--'TFO000049' --'JPE-17000146'
--AND rct.previous_customer_trx_id IS NOT NULL
;

SELECT RCT2.ORG_ID,
       RCT2.TRX_NUMBER, --first
       RCT2.CUST_TRX_TYPE_ID TRX_ID,
       RCT2.BATCH_SOURCE_ID,
       (SELECT BSRC.NAME
          FROM RA_BATCH_SOURCES_ALL BSRC
         WHERE 1 = 1
           AND BSRC.BATCH_SOURCE_ID = RCT2.BATCH_SOURCE_ID) SRC,
       RCT2.CREATION_DATE,
       (SELECT RCTT.NAME
          FROM RA_CUST_TRX_TYPES_ALL RCTT
         WHERE 1 = 1
           AND RCTT.CUST_TRX_TYPE_ID = RCT2.CUST_TRX_TYPE_ID
           AND ROWNUM = 1) NAME1,
       RCT.TRX_NUMBER,
       RCT.CUST_TRX_TYPE_ID,
       RCT.BATCH_SOURCE_ID,
       (SELECT BSRC.NAME
          FROM RA_BATCH_SOURCES_ALL BSRC
         WHERE 1 = 1
           AND BSRC.BATCH_SOURCE_ID = RCT.BATCH_SOURCE_ID
           AND ROWNUM = 1) SRC2,
       RCT.CREATION_DATE,
       (SELECT RCTT.NAME
          FROM RA_CUST_TRX_TYPES_ALL RCTT
         WHERE 1 = 1
           AND RCTT.CUST_TRX_TYPE_ID = RCT.CUST_TRX_TYPE_ID
           AND ROWNUM = 1) NAME2
  FROM RA_CUSTOMER_TRX_ALL RCT, --second
       RA_CUSTOMER_TRX_ALL RCT2 --first
 WHERE 1 = 1
   AND RCT2.CUSTOMER_TRX_ID = RCT.PREVIOUS_CUSTOMER_TRX_ID(+)
      --AND rct.previous_customer_trx_id IS NOT NULL
   AND RCT2.TRX_NUMBER LIKE /*'JPE-18000152'*/
       '%JPE%'
      --AND rct.org_id = 101
   AND RCT2.CREATION_DATE <= TO_DATE('20180315', 'yyyymmdd')
 ORDER BY RCT2.CREATION_DATE DESC;

SELECT BSRC.NAME
  FROM RA_BATCH_SOURCES_ALL BSRC
 WHERE 1 = 1
   AND BSRC.BATCH_SOURCE_ID = -1 --4008--rct.batch_source_id
;
