select C.REQUEST_GROUP_NAME, C.REQUEST_GROUP_CODE
  FROM FND_CONCURRENT_PROGRAMS_VL A,
       FND_REQUEST_GROUP_UNITS    B,
       FND_REQUEST_GROUPS         C
 WHERE A.CONCURRENT_PROGRAM_NAME = 'XXPJMR017'
   AND A.CONCURRENT_PROGRAM_ID = B.REQUEST_UNIT_ID
   AND A.APPLICATION_ID = B.UNIT_APPLICATION_ID
   AND B.REQUEST_GROUP_ID = C.REQUEST_GROUP_ID
