SELECT * FROM ZX_REGIMES_B ZRB WHERE 1 = 1;

SELECT * FROM ZX.ZX_TAXES_B# ZT WHERE 1 = 1;
SELECT *
  FROM ZX_TAXES_B ZT
 WHERE 1 = 1
   AND ZT.EFFECTIVE_TO IS NULL;

SELECT * FROM ZX_STATUS_B ZS WHERE 1 = 1 
AND zs.tax_status_code = 'CN_TAX_STATUS' FOR UPDATE
;

SELECT *
  FROM --ZX_JURISDICTIONS_VL
       zx.ZX_JURISDICTIONS_B ZJ
 WHERE 1 = 1
 AND zj.TAX_JURISDICTION_CODE = 'CN_TAX_JUR' FOR UPDATE;
 
 --Recovery code
 SELECT * FROM ZX_RATES_B zr
 WHERE 1=1
 --AND zr.tax_rate_code = 'CN_TAX_RECOVERY' FOR UPDATE
 AND zr.tax_rate_code = 'CN_TAX_RATE' 
 ;
 
 --tax rate
 
 --Recovery code
 SELECT * FROM ZX_RATES_B zr
 WHERE 1=1
 AND zr.tax_rate_code = 'CN_TAX_RATE' FOR UPDATE
 ;

SELECT ZDFV.DETERMINING_FACTOR_CLASS_CODE,
       ZDFV.DETERMINING_FACTOR_NAME,
       ZDFV.DETERMINING_FACTOR_DESC,
       ZDFB.CREATED_BY,
       (SELECT F.USER_NAME
          FROM FND_USER F
         WHERE 1 = 1
           AND F.USER_ID = ZDFB.CREATED_BY) CREATOR,
       ZDFB.*
  FROM ZX_DETERMINING_FACTORS_B ZDFB, ZX_DETERMINING_FACTORS_VL ZDFV

 WHERE 1 = 1
   AND ZDFB.DETERMINING_FACTOR_CODE = ZDFV.DETERMINING_FACTOR_CODE --ZDFV.DETERMINING_FACTOR_CLASS_CODE

;

--Determining factor sets
SELECT * FROM ZX.ZX_DETERMINING_FACTORS_B#;

SELECT (SELECT F.USER_NAME
          FROM FND_USER F
         WHERE 1 = 1
           AND F.USER_ID = ZC.CREATED_BY) CREATOR,
       ZC.ALPHANUMERIC_VALUE,
       ZC.VALUE_LOW,
       ZC.*
  FROM ZX_CONDITIONS ZC
 WHERE 1 = 1
--AND zc.
;

--纳税条件集
SELECT * FROM ZX_CONDITION_GROUPS_B
;
