--org_id      Resp_id     Resp_app_id        Organization_id
--HBS 101     51249       660                HB1  121
--HEA 82      50676       660                SG1  83
--HET 141     51272       20005              HE1  161
--SHE 84      50778       20005              TH1  85  TH2 86

/*BEGIN
  fnd_global.apps_initialize(user_id      => 4270,
                             resp_id      => 51249,
                             resp_appl_id => 660);
  mo_global.init('M');
  --FND_PROFILE.PUT('MFG_ORGANIZATION_ID', 86);
  
END;*/

SELECT /*row_id,
       org_id,
       operating_unit,
       header_id,
       customer_id,
       customer_number,
       customer_name,
       bill_to_site_use_id,
       ship_from,
       bill_to_address1,
       bill_to_address2,
       bill_to_address3,
       ship_to_site_use_id,
       ship_to_address1,
       ship_to_address2,
       ship_to_address3,
       transpotation_code,
       project_number,
       project_name,
       ship_remark,
       remark,
       oe_header_id,
       invoice_type,
       invoice_type_code,
       invoice_number,
       case_delivery_id,
       so_number,
       cust_po_number,
       lc_number,
       salesman,
       invoice_date,
       payment_term_name,
       due_date,
       etd_date,
       delivery_number,
       eta_date,
       delivery_term,
       status_code,
       attention_party,
       project_id,
       gst_code,
       tax_rate,
       gst_tax_rate_id,
       mandatory_match_so_flag,
       last_invoice_flag,
       salesrep_id,
       currency_code,
       payment_term_id,
       interest_rate,
       comments,
       payment_term_des,
       document_type,
       doc_prefix,
       match_delivery_flag,
       ar_trx_type_id,
       ar_batch_source_id,
       created_from,
       attribute_category,
       attribute1,
       attribute2,
       attribute3,
       attribute4,
       attribute5,
       attribute6,
       attribute7,
       attribute8,
       attribute9,
       attribute10,
       attribute11,
       attribute12,
       attribute13,
       attribute14,
       attribute15,
       creation_date,
       last_updated_by,
       last_update_date,
       created_by,
       last_update_login,
       program_application_id,
       program_id,
       program_update_date,
       request_id*/*
  FROM xxar_tax_invoice_headers
 WHERE (header_id = 10363)
