SELECT PV.VENDOR_NAME AS 供应商名称,
       PV.SEGMENT1 AS 供应商编号,
       PV.VENDOR_TYPE_LOOKUP_CODE AS 供应商类型,
       PV.END_DATE_ACTIVE AS 状态失效时间,
       TAX.TAX_REFERENCE AS 纳税登记编号,
       TAX.JGZZ_FISCAL_CODE AS 纳税人标识,
       PVS.VENDOR_SITE_CODE AS 地点名,
       PVS.ADDRESS_LINE1 AS 地址,
       pvs.zip AS 邮政编码,
       pvs.zip AS 公司邮政编码,
       PVS.AREA_CODE || ' ' || PVS.PHONE AS 声音,
       CON.FAX_PHONE_AREA_CODE || CON.FAX_PHONE_NUMBER AS 传真,
       TERMS.NAME AS 付款条件,
       PVS.PAYMENT_METHOD_LOOKUP_CODE AS 付款方法,
       IEBA.BANK_ACCOUNT_NUM AS 银行账户,
       --ieba.CONTACT_NAME,
       bank.PARTY_NAME AS 开户行,
       --PVS.BANK_ACCOUNT_NUM AS 银行账户,
       --PVS.BANK_ACCOUNT_NAME AS 开户行,
       pv.VENDOR_NAME_ALT AS 账户持有人,
       PV.INVOICE_CURRENCY_CODE AS 订单货币,
       CON.PERSON_LAST_NAME || ' ' || CON.PERSON_MIDDLE_NAME || ' ' ||
       CON.PERSON_FIRST_NAME AS 联系人姓名,
       9999999 AS 位置,
       CON.PHONE_AREA_CODE || CON.PHONE_NUMBER AS 电话,
       9999999 AS 语言,
       CON.EMAIL_ADDRESS AS 邮箱,
       
       PVS.ORG_ID
       --pv.*
  FROM PO_VENDORS PV,
       AP_TERMS_TL TERMS,
       PO_VENDOR_CONTACTS PVC,
       PO_VENDOR_SITES_ALL PVS,
       IBY_ACCOUNT_OWNERS IAO, --IBY_EXT_BANK_ACCOUNTS
       IBY_EXT_BANK_ACCOUNTS IEBA,
       HZ_PARTIES BANK,
       HZ_PARTIES BRANCH,
       HZ_PARTIES TAX,
       (SELECT HR.SUBJECT_ID         SUBJECT_ID,
               HR.OBJECT_ID          OBJECT_ID,
               HR.PARTY_ID           PARTY_ID,
               HP.PERSON_LAST_NAME,
               HP.PERSON_MIDDLE_NAME,
               HP.PERSON_FIRST_NAME,
               HP.POSTAL_CODE,
               HCPP.PHONE_AREA_CODE  PHONE_AREA_CODE,
               HCPP.PHONE_NUMBER     PHONE_NUMBER,
               HCPP.PHONE_EXTENSION  PHONE_EXTENSION,
               HCPF.PHONE_AREA_CODE  FAX_PHONE_AREA_CODE,
               HCPF.PHONE_NUMBER     FAX_PHONE_NUMBER,
               HCPE.EMAIL_ADDRESS    EMAIL_ADDRESS
          FROM HZ_RELATIONSHIPS  HR,
               HZ_CONTACT_POINTS HCPP,
               HZ_CONTACT_POINTS HCPF,
               HZ_CONTACT_POINTS HCPE,
               HZ_PARTIES        HP
         WHERE HR.OBJECT_ID = HP.PARTY_ID
           AND HCPP.OWNER_TABLE_ID(+) = HR.PARTY_ID
           AND HCPF.OWNER_TABLE_ID(+) = HR.PARTY_ID
           AND HCPE.OWNER_TABLE_ID(+) = HR.PARTY_ID
           AND HR.OBJECT_TYPE = 'PERSON'
           AND HR.RELATIONSHIP_CODE(+) = 'CONTACT'
           AND HCPP.OWNER_TABLE_NAME(+) = 'HZ_PARTIES'
           AND HCPF.OWNER_TABLE_NAME(+) = 'HZ_PARTIES'
           AND HCPE.OWNER_TABLE_NAME(+) = 'HZ_PARTIES'
           AND HCPP.CONTACT_POINT_TYPE(+) = 'PHONE'
           AND HCPP.PHONE_LINE_TYPE(+) = 'GEN'
           AND HCPF.CONTACT_POINT_TYPE(+) = 'PHONE'
           AND HCPF.PHONE_LINE_TYPE(+) = 'FAX'
           AND HCPE.CONTACT_POINT_TYPE(+) = 'EMAIL'
           AND HCPE.PHONE_LINE_TYPE IS NULL) CON

 WHERE PV.VENDOR_ID = PVS.VENDOR_ID
      
   AND TERMS.TERM_ID(+) = PVS.TERMS_ID
   AND PVS.VENDOR_SITE_ID = PVC.VENDOR_SITE_ID(+)
   AND PVS.VENDOR_ID = PVC.VENDOR_ID(+)
   AND PV.PARTY_ID = TAX.PARTY_ID(+)
   AND PV.PARTY_ID = IAO.ACCOUNT_OWNER_PARTY_ID(+)
   AND IAO.EXT_BANK_ACCOUNT_ID = IEBA.EXT_BANK_ACCOUNT_ID(+)
   AND IEBA.BANK_ID = BANK.PARTY_ID(+)
   AND IEBA.BRANCH_ID = BRANCH.PARTY_ID(+)
   AND PV.PARTY_ID = CON.SUBJECT_ID(+)
   --AND pv.vendor_id = 492354
   --AND terms.LANGUAGE <> 'US'
   AND PVS.ORG_ID = 82--1129 --HNET
   --AND PV.SEGMENT1 IN ( /*'BJZJ01H',*/ 'AMSF01H') --'BJZJ01H'--'AMSF01H' --'BJZJ01H'
AND   pv.segment1 = 'FB00003722'--'FB00003722'--'FB00003722'--'FB00003016'--'BJZJ01H'
--AND PV.VENDOR_NAME = 'WLC FACILITIES SERVICES PTE LTD'--'THE BANK OF TOKYO-MITSUBISHI UFJ, L'
--AND pvs.BANK_ACCOUNT_NUM IS NOT NULL
;
