SELECT *
  FROM BNE_INTEGRATORS_B T
 WHERE T.INTEGRATOR_CODE = 'GENERAL_165_INTG'; --存贮WebADI集成器
SELECT *
  FROM BNE_CONTENTS_B T
 WHERE T.INTEGRATOR_CODE = 'GENERAL_165_INTG'; --存贮集成器对应内容信息，其中content_class列决定了报表的内容。如集成器General Ledger - Journals中有两个内容：None 和Text（具体细节没有研究，大家有时间可以研究一下）
SELECT *
  FROM BNE_CONTENT_COLS_B T
 WHERE T.CONTENT_CODE = 'GENERAL_165_CNT';
 
SELECT * FROM BNE_PARAM_LISTS_B T WHERE T. GENERAL_165_INTG; --：参数列表，可以理解为参数的分组。目的是为了实现参数的重用

SELECT * FROM BNE_PARAM_LIST_ITEMS; --：存贮参数列表和参数的关联信息

SELECT *
  FROM BNE_PARAM_DEFNS_B T
 WHERE T.PARAM_DEFN_CODE LIKE 'HSS%SESSION%'; --：存贮参数定义，包括默认值、验证信息、显示信息等。

SELECT *
  FROM DBA_OBJECTS DO
 WHERE DO.OBJECT_NAME LIKE 'BNE%LAYOUT%'
   AND DO.OBJECT_TYPE = 'TABLE';
SELECT * FROM BNE_LAYOUTS_B T WHERE T.INTEGRATOR_CODE = 'GENERAL_165_INTG'; ---布局
SELECT * FROM BNE_COMPONENTS_B; --组建
SELECT * FROM BNE_LAYOUT_COLS T WHERE T.LAYOUT_CODE = 'HPOS_INVORDERS'; --布局的行
