SELECT * FROM ORG_ORGANIZATION_DEFINITIONS OOD;

SELECT *
  FROM HR_OPERATING_UNITS HOU
 WHERE 1 = 1
 ORDER BY HOU.BUSINESS_GROUP_ID;

--Vision China
/*
organization_id 4555
*/

SELECT *
  FROM RA_CUSTOMER_TRX_ALL RCT
 WHERE 1 = 1
   AND RCT.ORG_ID = 4555;
