SELECT R.RESPONSIBILITY_NAME
  FROM APPS.FND_REQUEST_GROUP_UNITS GU,
      APPS.FND_REQUEST_GROUPS      G,
       APPS.FND_RESPONSIBILITY_VL   R
 WHERE GU.REQUEST_UNIT_ID in ('125610','20011') --Clear Expire Date Program & Addon PA
   AND GU.REQUEST_GROUP_ID = G.REQUEST_GROUP_ID
   AND R.REQUEST_GROUP_ID = G.REQUEST_GROUP_ID
