--应收发票
SELECT ART.BATCH_NUMBER,
       ART.TRX_NUMBER,
       ART.TRX_TYPE,
       ART.CREATION_DATE,
       ART.ORG_NAME,
       ART.PROCESS_STATUS_LOOKUP_CODE 处理里状态,
       ART.PROCESS_MESSAGE,
       ART.*
  FROM APPS.CUX_AR_WS_CUST_TRX_ITF_V ART
 WHERE 1 = 1
   AND ART.PROCESS_STATUS_LOOKUP_CODE <> 'SUCCESS'
   AND ART.ORG_NAME LIKE '%ZJ%'
   --AND ART.CREATION_DATE > TRUNC(SYSDATE)
   ;
